/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jniandroidtest1_imageProc */

#ifndef _Included_jni_binarysearch
#define _Included_jni_binarysearch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jniandroidtest1_imageProc
 * Method:    grayproc
 * Signature: ([III)[I
 */
JNIEXPORT jboolean JNICALL Java_com_jni_ImgDealJni_binarySearch
  (JNIEnv *, jclass , jint);

#ifdef __cplusplus
}
#endif
#endif
