/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jniandroidtest1_imageProc */

#ifndef _Included_jni_ImgDealJni
#define _Included_com_ImgDealJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jniandroidtest1_imageProc
 * Method:    grayproc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jni_ImgDealJni_Rgb2Gray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
